### PR TITLE
Added HalvesRainbow class which animates pixels in a rainbow either from...

### PR DESCRIPTION
**Pull request by webmonger**
... the centre or from the outside in. You can increase the steps through the rainbow using rainbow_inc

### CODE REVIEW

**Comment by adammhaile** [comment]
Thanks! Could you add all the readme details into the animation files themselves? I would like to keep everything self contained.

**Comment by webmonger** [comment]
Yes no problem, I'll do that later

**Comment by adammhaile** [comment]
@webmonger 
Just a reminder to add all the readme details to the animation files, then I'll pull this in :)

**Comment by webmonger** [comment]
Cheers, Sorry been very busy with work which has not provided me with much time for external projects over the last few weeks. I hope to be able to come back to this in a couple of weeks probably mid June :)

**Comment by adammhaile** [comment]
No worries. I can just make the changes if you would prefer. Just wanted to
give you the option.

**Comment by webmonger** [comment]
Hey @adammhaile I've updated the previous pull requests moving the documentation from Readme.md to the individual files. I've not managed to write the final one yet but when I'm back home in a few days I'll get that finished.

**Pull request merged**
